### ISSUE TITLE
2021_05_10 - SIPR Feedback Form - Times

### ISSUE THREAD

**Issue by CTOverton** [CTOverton/siepser-projects#162]
> Note: Waiting for doctor names and devices lists

## Todo
- [x] Create a Google form in [Siepser Drive](https://drive.google.com/drive/folders/1BBqCYcVp2SCD5uKtxfXv-LnO3S-oqWYc?usp=sharing)
- [x] Style it using Siepser branding
- [x] Reply to this issue and provide link to form for review

### Questions

Question Label | Type | Description
------------ | ------------- | -------------
Name | Dropdown of doctor Names | 
Case number | Number | Surgical case number
Device | Dropdown of devices | 
Total time | Duration of minutes and seconds | How long did it take to manipulate the device into position?
Total time | Duration of minutes and seconds | How long did it take to remove the device?

#### Doctors
> Order alphabetically

- David Gano
- Brian Kim
- Ravi Goel
- Blake Williamson
- Reza Razeghinejad
- Jared R. Younger MD
- Suphi Taneri
- Jack Parker
- Craig Chaya
- William Wiley
- Alberto Martinez
- Sam Van Roon

#### Devices
> Order by popularity

1. Malyugin Ring 2.0
2. Hooks
3. Oasis
4. VisitecI-Ring
5. Eagle Vision Graether Ring
6. FCI Morcher
7. Assia Pupil Expander
8. AJL Canabrava
9. B-D Milvella
10. M I DB-HEX
11. Diamatrix Xpand NT
12. Grieshaber Hydroview

### Siepser Branding
- [Brand colors](https://shared-assets.adobe.com/link/bad73b15-3e3e-4879-6d92-ea9226afc513)
- [Logo](https://drive.google.com/drive/folders/1ffpgfulTNjgMOZ9pFT_VB9DKkTrlQYsR?usp=sharing)
